
# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres
    restart: always
    container_name: postgres1

    environment:
      POSTGRES_USER: caleb
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: test
    ports:
      - "5432:5432"
    restart: always 
  
